---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: mongodb
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: mongodb
    version: 7.6.3
  values:
    image:
      repository: bitnami/mongodb
      tag: 4.0.13
    usePassword: false
    persistence:
      enabled: false