---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: myprom
  namespace: default
spec:
  releaseName: myprom
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-community/kube-prometheus-stack
    version: 14.6.2
  values:
    grafana:
      adminPassword: ed0ef863f6dc9c7f