name: Self-Hosted byukd
on:
  push:
    branches:
      - main
  release:
    tags:
      - 'v*.*.*'
jobs:
  build-and-publish:
    name: Build and Publish Main
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: update version
        run: |
              echo "${GITHUB_REF##*/}" > ./app/version
              cat ./app/version

      - name: Set Up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2.4.0
        with:
          path: app
          repository: 347041458788.dkr.ecr.eu-west-3.amazonaws.com/fluxcd-test
          tag_with_ref: true